### ISSUE TITLE
web-app-launcher not working

### ISSUE THREAD

**Issue by kercos** [MBoretto/easy-qr-scan-bot#5]
when running `web-app-launcher.py` I get the following error:

```
web-app-launcher.py", line 64, in main
    updater = Updater(TELEGRAM_API_TOKEN)
TypeError: __init__() missing 1 required positional argument: 'update_queue'
```

It looks like the [Updater](https://docs.python-telegram-bot.org/en/v20.7/telegram.ext.updater.html) in the most recent version of PTB requires a second argument but only one is specified in the current code.

**Comment by MBoretto** [comment]
Hi @kercos, thanks for reporting!
I think the best is to update the  code and make it work with the new function. I will check that as soon as I have time!
Anyway, in case you manage to fix it yourself I would be happy to merge your code!
What version are you using?

**Comment by kercos** [comment]
Hi @MBoretto,
I'm currently running PTB 20.6.
If I'm able to solve it, I'll let you know.
